[package]
name = "openai-natsuki-bot"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.97"
mastodon-async = { git = "https://github.com/dscottboggs/mastodon-async", branch = "comb", version = "1.3.2", features = ["json", "mt"] }
tokio = { version = "1.44.1", features = ["full"] }
toml = "0.8.20"
tracing = "0.1.41"
tracing-subscriber = "0.3.19"
