services:
  bot:
    build: "."
    user: "1000:1000"
    environment:
      TZ: "Asia/Tokyo"
    volumes:
      - "./config.toml:/config.toml"
      - "./conversations.sqlite3:/conversations.sqlite3"
