services:
  bot:
    build: "."
    environment:
      TZ: "Asia/Tokyo"
      RUST_LOG: "info,mastodon_async=warn"
    volumes:
      - "./config.toml:/config.toml:ro"
      - "./conversations.sqlite3:/conversations.sqlite3"
