services:
  bot:
    build:
      context: "."
      args:
        GIT_COMMIT_HASH: "unknown"
    stop_grace_period: "2s"
    environment:
      TZ: "Asia/Tokyo"
      RUST_LOG: "warn,lnb_server=info,lnb_mastodon_client=info,lnb_discord_client=info"
    volumes:
      - "./data:/data"
