services:
  bot:
    build:
      context: "."
      args:
        GIT_COMMIT_HASH: "unknown"
    stop_grace_period: "2s"
    environment:
      TZ: "Asia/Tokyo"
      RUST_LOG: "info,mastodon_async=warn"
    volumes:
      - "./data:/data"
