FROM mirror.gcr.io/node:22 AS builder
ENV NODE_ENV=development
WORKDIR /build
COPY lnb-math-renderer/package*.json ./
COPY lnb-math-renderer/tsconfig.json ./
RUN npm ci
COPY lnb-math-renderer/src ./src
RUN npm run build
WORKDIR /font
RUN mkdir -p /usr/local/share/fonts \
    && wget https://github.com/githubnext/monaspace/releases/download/v1.301/monaspace-static-v1.301.zip \
    && unzip monaspace-static-v1.301.zip \
    && find -name '*.otf' -exec cp -t /usr/local/share/fonts {} +


FROM mirror.gcr.io/node:22-slim AS runtime
ENV NODE_ENV=production
RUN apt-get update && apt-get install -y fontconfig \
    && rm -rf /var/lib/apt/lists/*
COPY --from=builder /usr/local/share/fonts/* /usr/local/share/fonts/
RUN fc-cache -fv
WORKDIR /app
COPY lnb-math-renderer/package*.json ./
COPY lnb-math-renderer/tsconfig.json ./
RUN npm ci --omit=dev
COPY --from=builder /build/dist ./dist
USER node
EXPOSE 3000
CMD ["node", "dist/index.js"]
