[package]
name = "lnb-daily-private"
version.workspace = true
description.workspace = true
authors.workspace = true
edition.workspace = true

[dependencies]
rand = { workspace = true }
serde = { workspace = true }
time = { workspace = true }
