name: "Build Docker Image"

on:
  workflow_dispatch:


permissions:
  contents: "read"
  packages: "write"
  attestations: "write"
  id-token: "write"

env:
  REGISTRY: "ghcr.io"
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    name: "Build"
    runs-on: "ubuntu-latest"
    steps:
      - name: "Checkout"
        uses: "actions/checkout@v4"

      - name: "Login"
        uses: docker/login-action@74a5d142397b4f367a81961eba4e8cd7edddf772
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: "Fetch metadata"
        uses: "docker/metadata-action@902fa8ec7d6ecbf8d84d538b9b233a880e428804"
        id: "meta"
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: "Build and push Docker image"
        id: push
        uses: docker/build-push-action@84ad562665bb303b549fec655d1b64f9945f3f91
        with:
          context: .
          file: "./docker/Dockerfile.lnb-server"
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            GIT_COMMIT_HASH=${{ github.sha }}

      - name: "Generate artifact attestation"
        uses: "actions/attest-build-provenance@v2"
        with:
          subject-name: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          subject-digest: ${{ steps.push.outputs.digest }}
          push-to-registry: true
